openapi: 3.0.0

servers:
  - url: 'localhost'
info:
  description: >-
    This is Esquire Rest API for backoffice tree navigation.
  version: 1.0.0
  title: Esquire Frameworks(tm) Backoffice API
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: esquire
    description: Everything you need to browse Esquire tree
paths:
  /esq:
    get:
      tags:
        - esquire
      summary: Retrieve list of tree nodes
      description: Retrieve list of child tree nodes for the node
      operationId: esquire
      parameters:
        - name: id
          in: query
          description: parent node id or missed to obtain root nodes
          required: false
          schema:
            type: string
        - name: skip
          in: query
          description: number of nodes to skip
          required: false
          schema:
            type: integer
            format: int32
        - name: take
          in: query
          description: number of nodes to obtain
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EsqTreeNode'
        '405':
          description: Invalid input
  /esq-path:
    get:
      tags:
        - esquire
      summary: Retrieve a path of a node
      description: Retrieve a path of a node (a location where a node located in the tree)
      operationId: esquirePath
      parameters:
        - name: id
          in: query
          description: a node id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '405':
          description: Invalid input
  /esq-cmd:
    get:
      tags:
        - esquire
      summary: Generic esquire command
      description: Open interface to call a specific command, default cmd is 'details'
                   to obtain properties on an entity by its id
      operationId: esquireCmd
      parameters:
        - name: kind
          in: query
          description: an entity type
          required: true
          schema:
            type: integer
            format: int32
        - name: id
          in: query
          description: An id of node or entity, depends on command context
          required: true
          schema:
            type: string
        - name: cmd
          in: query
          description: a command to process , default 'details'
          required: false
          schema:
            type: string
            default: details
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
        '405':
          description: Invalid input
  /esq-enode:
    get:
      tags:
        - esquire
      summary: Find an entity node
      description: Find a node corresponding to the entity's id or name + kind
      operationId: esquireEntityNode
      parameters:
        - name: kind
          in: query
          description: an entity type
          required: true
          schema:
            type: integer
            format: int32
        - name: id
          in: query
          description: an entity id
          required: false
          schema:
            type: string
        - name: name
          in: query
          description: an entity name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EsqTreeNode'
        '405':
          description: Invalid input
  /esq-dict:
    get:
      tags:
        - esquire
      summary: Obtain a dictionary of an entity
      description: Obtain a dictionary of an entity by its kind
      operationId: esquireDictionary
      parameters:
        - name: kind
          in: query
          description: an entity kind
          required: required
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EsqEntityLayer'
        '405':
          description: Invalid input
  /esq-kinds:
    get:
      tags:
        - esquire
      summary: Obtain a list of object kinds
      description: Obtain a list of object kinds
      operationId: esquireKinds
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EsqObjectKind'
        '405':
          description: Invalid input
  /esq-key:
    get:
      tags:
        - esquire
      summary: Obtain an access profile
      description: Obtain an access profile of a user
      operationId: esquireKey
      parameters:
        - name: id
          in: query
          description: a user id
          required: optional
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/definitions/EsqAccessProfile'
        '405':
          description: Invalid input
  /esq-cmd-save:
    post:
      tags:
        - esquire
      summary: Save entity changes
      description: Save changed fields of an entity
      operationId: esquireCmdSave
      parameters:
        - name: kind
          in: query
          description: an entity type
          required: true
          schema:
            type: integer
            format: int32
        - name: id
          in: query
          description: an entity id
          required: true
          schema:
            type: string
        - name: cmd
          in: query
          description: a command to process
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EsqEntity'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EsqEntity'
        '405':
          description: Invalid input
  /esq-cmd-asave:
    post:
      tags:
        - esquire
      summary: Save account entity changes
      description: Save changed fields of an account entity
      operationId: esquireCmdAsave
      parameters:
        - name: kind
          in: query
          description: an entity type
          required: true
          schema:
            type: integer
            format: int32
        - name: id
          in: query
          description: an entity id
          required: true
          schema:
            type: string
        - name: cmd
          in: query
          description: a command to process
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EsqEntity'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EsqEntity'
        '405':
          description: Invalid input
  /esq-key-save:
    post:
      tags:
        - esquire
      summary: Save access profile changes
      description: Save changed fields of an access profile
      operationId: esquireKeySave
      parameters:
        - name: id
          in: query
          description: a user id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EsqAccessProfile'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EsqAccessProfile'
        '405':
          description: Invalid input

components:
  schemas:
    EsqEntity:
      title: Entity
      description: An entity with identity and dynamic fields defined by dictionary
      type: object
      properties:
        id:
          type: string
          description: Entity id
        kind:
          type: integer
          format: int32
          description: Entity kind
      additionalProperties: true
    EsqTreeNode:
      title: Tree Node
      description: A node with all information for tree navigation
      type: object
      properties:
        id:
          type: string
          description: node id
          example: Pikachu
        kind:
          type: integer
          format: int32
          description: Node type, odd types are 'short cuts' a link node referencing to origin one
          example: 13
        name:
          type: string
          description: Node name
          example: Pikachu
        parentId:
          type: string
          description: Parent node id
          example: Pokemons
        linkId:
          type: string
          description: For shortcut nodes, reference to the origin node
          example: Pikachu
        entityId:
          type: string
          description: Entity id (it can be different from node id)
          example: Pikachu
        statusCode:
          type: integer
          format: int32
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
          description: Node Status Code, (0)ok (1)deleted (2)locked, (3)checked (4)question
          example: 0
        moreRemaining:
          type: boolean
          description: Indicates when more nodes left to retrieve
          example: false
        level:
          type: integer
          format: int32
          description: Tree level of node
          example: 2
        path:
          type: array
          items:
            type: string
          description: Node path on the tree
          example: [root,Pokemons]
        desc:
          type: string
          description: Node description
          example: Yellow Electric Mouse Pokemon
      xml:
        name: EsqTreeNode
    EsqEntityLayer:
      title: Tree entity details layer
      description: An UI layer (or tab) aggregating a set of entity fields
      type: object
      properties:
        title:
          type: string
          description: a layer heading
          example: Generic
        fields:
          type: array
          description: set of entity field definitions
          items:
            $ref: '#/components/schemas/EsqEntityField'
    EsqEntityField:
      title: Tree entity field definition
      description: Tree entity field metadata
      type: object
      properties:
        name:
          type: string
          description: name of the field
          example: hight
        sort:
          type: integer
          format: int32
          description: position in the sorting order
          example: 3
        label:
          type: string
          description: GUI field label
          example: Hight
        type:
          type: string
          description: Type of field data
          enum:
            - string
            - flag
            - integer
            - number
            - datetime
            - tablist
            - tabstring
            - href
            - image
          example: string
        tooltip:
          type: string
          description: GUI tooltip over the field
          example: Pokemon height in meters
        listvalues:
          type: array
          items:
            type: string
          description: possible values in dropdown list UI element
        nullable:
          type: boolean
          description: Determines whether the field value can be null
          example: false
        nullmeaning:
          type: string
          description: a meaning of null value for UI representation
        validation:
          type: string
          description: a validation regex for UI input
          example:  '^[Z0-9]+$'
        layer:
          type: integer
          format: int32
          description: an UI layer of the filed
          example: 1
        readwrite:
          type: integer
          format: int32
          enum:
            - 0
            - 1
            - 3
          description: A bitmap (0)hidden (1)view (3)full
          example: 1
        format:
          type: string
          description: For tablist field - a kind of entities represented in the list; for string - max length; for integer, number, datetime- format
    EsqRole:
      title: Access Profile
      description: Access Profile of a user
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Role ID
          example: 100
        name:
          type: string
          description: Role Name
          example: TREE
        adminFlg:
          type: string
          description: Role Name
          example: TREE
    EsqPermission:
      title: User Permission
      description: User Permission
      type: object
      properties:
        id:
          type: string
          description: Permission ID
          example: 112
        kind:
          type: integer
          format: int32
          description: Kind  of user were access defined
          example: 12
        name:
          type: string
          description: Type of permission
          example: Client
        type:
          type: string
          description: Type of permission
          example: Admin
        flags:
          type: array
          items:
            type: string
          description: "Permission Y/N flags: create, update, delete, security, accounting"
    EsqAccessProfile:
      title: Access Profile
      description: Access Profile of a user
      type: object
      properties:
        id:
          type: string
          description: User ID
          example: 6
        kind:
          type: integer
          format: int32
          description: Kind  of user
          example: 12
        name:
          type: string
          description: User name
          example: Vasiia Pupkin
        loginId:
          type: string
          description: User Login ID
          example: mainadmin
        email:
          type: string
          description: User email
          example: pasilii.pupkin@gmail.com
        pwdChangeForced:
          type: string
          enum:
            - Y
            - N
          description: Y/N Flag to force password change
          example: N
        tfaMethod:
          type: string
          enum:
            - N
            - G
            - g
          description: Method of 2 factor authentication, N:not set, G:google authenticator, g:google authenticator pending"
          example: N
        roles:
          type: array
          description: List of roles assigned to user
          items:
            $ref: '#/components/schemas/EsqRole'
        permissions:    
          type: object
          description: Grouped permissions assigned to user
          properties:
            admin:
              type: array
              description: Admin permissions
              items:
                $ref: '#/components/schemas/EsqPermission'
            tools:
              type: array
              description: List of user tools and applications
              items:
                $ref: '#/components/schemas/EsqPermission'
          additionalProperties: false            
    EsqObjectKind:
      title: Object Kind
      description: Object Kind
      type: object
      properties:
        id:
          type: integer
          format: int32
          description: Object Kind id
          example: 1
        name:
          type: string
          description: Name of kind, in lower case
          example: system
        title:
          type: string
          description: Verbal name of kind
          example: System
        plural:
          type: string
          description: Plural name, in lower case
          example: systems
        desc:
          type: string
          description: Description of kind
          example: Esquire system root
        org:
          type: boolean
          description: Defines Organization kind
        usr:
          type: boolean
          description: Defines User kind
        acct:
          type: boolean
          description: Defines Account kind
        icon:
          type: string
          description: Name of type icon
          example: img/system.ico
        detailed:
          type: boolean
          description: Flags an entity, has details
        childrenDetailed:
          type: boolean
          description: Flags that entity has children listed in details screen
        treeFlags:
          type: string
          description: Tree flags
          example: BTb
        listHeaders:
          type: array
          description: List of heading columns for list view {column name, column header}
          items:
            $ref: '#/components/schemas/EsqColumnHeaderDef'
        childKinds:
          type: array
          items:
            type: integer
            format: int32
          description: List of entity kinds can be created within the entity
          example: [30,32]
        commands:
          type: array
          items:
            type: string
          description: List of entity commands
          example: [move,key]
    EsqColumnHeaderDef:
      title: Column Header definition
      description: Column Header definition
      type: object
      properties:
        columnDef:
          type: string
          description: column definition
          example: name
        header:
          type: string
          description: Header title
          example: Entity Name
