/*
 *  Esquire frameworks (tm)
 *  Esquire Backend (BFF tier)
 *
 *  Copyright(c) 2001, 2026 mir0n&co www.mir0n.me
 *  mailto:mir0n.the.programmer@gmail.com
 *
 *  History:
 * 05/07/2026 mir0n  created: traceMiddleware; X-Request-ID generated per request; X-Correlation-ID propagated only when client sets it (gateway is canonical)
 */

import type { RequestHandler } from 'express';
import { randomUUID } from 'node:crypto';

const HDR_REQUEST_ID = 'x-request-id';
const HDR_CORRELATION_ID = 'x-correlation-id';

declare global {
  // eslint-disable-next-line @typescript-eslint/no-namespace
  namespace Express {
    interface Request {
      esqRequestId: string;
      // Optional: only present if the client (rare ad-hoc debug case) set
      // X-Correlation-ID on the inbound request. The BFF does NOT generate
      // its own -- the gateway is the canonical source of correlation IDs.
      esqCorrelationId: string | undefined;
    }
  }
}

/**
 * Esquire tracing-header convention (services/doc, reference_tracing_headers.md):
 *   X-Request-ID     - one UUID per outbound HTTP from the Esquire client.
 *                      Client-generated; if absent here, the BFF generates one
 *                      so internal logs stay correlatable.
 *   X-Correlation-ID - generated by the gateway, not the BFF. The BFF only
 *                      forwards what came in (typically nothing). The gateway's
 *                      RequestTraceFilter creates one if absent.
 *
 * Both IDs (when present) are echoed on the response and exposed on req for
 * downstream callers.
 */
export const traceMiddleware: RequestHandler = (req, res, next) => {
  const incomingRequestId = headerValue(req.headers[HDR_REQUEST_ID]);
  const incomingCorrelationId = headerValue(req.headers[HDR_CORRELATION_ID]);

  req.esqRequestId = incomingRequestId ?? randomUUID();
  req.esqCorrelationId = incomingCorrelationId;

  res.setHeader('X-Request-ID', req.esqRequestId);
  if (req.esqCorrelationId !== undefined) {
    res.setHeader('X-Correlation-ID', req.esqCorrelationId);
  }

  next();
};

function headerValue(raw: string | string[] | undefined): string | undefined {
  let ret: string | undefined;
  if (Array.isArray(raw)) {
    ret = raw[0];
  } else if (typeof raw === 'string' && raw.length > 0) {
    ret = raw;
  }
  return ret;
}
