/**
 *  Esquire frameworks (tm)
 *  Esqurie rest client
 *
 * Copyright(c) 2021, 2025 mir0n&co www.mir0n.me
 * mailto:mir0n.the.programmer@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


/**
 * Fields for posting an account transaction (deposit)
 */
export interface AcctTransactionRequest { 
    /**
     * Transaction type ID (from ESQ_ACTIVITY_TYPE table)
     */
    typeId: number;
    /**
     * Transaction amount; must be positive in Phase I
     */
    amount: number;
    /**
     * Transaction description
     */
    desc?: string;
    /**
     * Payment method (cash, check, credit card); null = n/a
     */
    refCode?: string;
    /**
     * Reference code
     */
    refCode2?: string;
    /**
     * Free-text memo
     */
    memo?: string;
    /**
     * When true, skips the negative-balance check (requires elevated permission)
     */
    skipValidation?: boolean;
}

