/**
 *  Esquire frameworks (tm)
 *  Esqurie rest client
 *
 * Copyright(c) 2021, 2025 mir0n&co www.mir0n.me
 * mailto:mir0n.the.programmer@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


/**
 * Result of a posted account transaction
 */
export interface AcctTransactionSimple { 
    /**
     * Transaction ID (ATR_PK)
     */
    id?: string;
    /**
     * Transaction entity kind (980 = accttr)
     */
    kind?: number;
    /**
     * Transaction type ID (ATR_AT_PK)
     */
    typeId?: number;
    /**
     * Amount posted to account
     */
    amount?: number;
    /**
     * Transaction description
     */
    desc?: string;
    /**
     * Payment method
     */
    refCode?: string;
    /**
     * Reference code
     */
    refCode2?: string;
    /**
     * Reserved for future use
     */
    refCode3?: string;
    /**
     * Reserved for future use
     */
    refCode4?: string;
    /**
     * Transaction memo
     */
    memo?: string;
}

