/**
 *  Esquire frameworks (tm)
 *  Esqurie rest client
 *
 * Copyright(c) 2021, 2025 mir0n&co www.mir0n.me
 * mailto:mir0n.the.programmer@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */
import { EsqPermission } from './esqPermission';


/**
 * Grouped permissions assigned to user
 */
export interface EsqAccessProfilePermissions { 
    /**
     * Admin permissions
     */
    admin?: Array<EsqPermission>;
    /**
     * List of user tools and applications
     */
    tools?: Array<EsqPermission>;
}

