/**
 *  Esquire frameworks (tm)
 *  Esqurie rest client
 *
 * Copyright(c) 2021, 2025 mir0n&co www.mir0n.me
 * mailto:mir0n.the.programmer@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */
import { EsqRole } from './esqRole';
import { EsqAccessProfilePermissions } from './esqAccessProfilePermissions';


/**
 * Access Profile of a user
 */
export interface EsqAccessProfile { 
    /**
     * User ID
     */
    id?: string;
    /**
     * Kind  of user
     */
    kind?: number;
    /**
     * User name
     */
    name?: string;
    /**
     * User Login ID
     */
    loginId?: string;
    /**
     * User email
     */
    email?: string;
    /**
     * Y/N Flag to force password change
     */
    pwdChangeForced?: EsqAccessProfile.PwdChangeForcedEnum;
    /**
     * Method of 2 factor authentication, N:not set, G:google authenticator, g:google authenticator pending\"
     */
    tfaMethod?: EsqAccessProfile.TfaMethodEnum;
    /**
     * List of roles assigned to user
     */
    roles?: Array<EsqRole>;
    permissions?: EsqAccessProfilePermissions;
}
export namespace EsqAccessProfile {
    export const PwdChangeForcedEnum = {
        Y: 'Y',
        N: 'N'
    } as const;
    export type PwdChangeForcedEnum = typeof PwdChangeForcedEnum[keyof typeof PwdChangeForcedEnum];
    export const TfaMethodEnum = {
        N: 'N',
        G: 'G',
        G2: 'g'
    } as const;
    export type TfaMethodEnum = typeof TfaMethodEnum[keyof typeof TfaMethodEnum];
}


