/**
 *  Esquire frameworks (tm)
 *  Esqurie rest client
 *
 * Copyright(c) 2021, 2025 mir0n&co www.mir0n.me
 * mailto:mir0n.the.programmer@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */
import { EsqEntityField } from './esqEntityField';


/**
 * An UI layer (or tab) aggregating a set of entity fields
 */
export interface EsqEntityLayer { 
    /**
     * a layer heading
     */
    title?: string;
    /**
     * set of entity field definitions
     */
    fields?: Array<EsqEntityField>;
}

