/**
 *  Esquire frameworks (tm)
 *  Esqurie rest client
 *
 * Copyright(c) 2021, 2025 mir0n&co www.mir0n.me
 * mailto:mir0n.the.programmer@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


/**
 * An entity with identity and dynamic fields defined by dictionary
 */
export interface EsqEntity { 
  [key: string]: any | any;


    /**
     * Entity id
     */
    id?: string;
    /**
     * Entity kind
     */
    kind?: number;
}

