/**
 *  Esquire frameworks (tm)
 *  Esqurie rest client
 *
 * Copyright(c) 2021, 2025 mir0n&co www.mir0n.me
 * mailto:mir0n.the.programmer@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */
import { EsqColumnHeaderDef } from './esqColumnHeaderDef';


/**
 * Object Kind
 */
export interface EsqObjectKind { 
    /**
     * Object Kind id
     */
    id?: number;
    /**
     * Name of kind, in lower case
     */
    name?: string;
    /**
     * Verbal name of kind
     */
    title?: string;
    /**
     * Plural name, in lower case
     */
    plural?: string;
    /**
     * Description of kind
     */
    desc?: string;
    /**
     * Defines Organization kind
     */
    org?: boolean;
    /**
     * Defines User kind
     */
    usr?: boolean;
    /**
     * Defines Account kind
     */
    acct?: boolean;
    /**
     * Name of type icon
     */
    icon?: string;
    /**
     * Flags an entity, has details
     */
    detailed?: boolean;
    /**
     * Flags that entity has children listed in details screen
     */
    childrenDetailed?: boolean;
    /**
     * Tree flags
     */
    treeFlags?: string;
    /**
     * List of heading columns for list view {column name, column header}
     */
    listHeaders?: Array<EsqColumnHeaderDef>;
    /**
     * List of entity kinds can be created within the entity
     */
    childKinds?: Array<number>;
    /**
     * List of entity commands
     */
    commands?: Array<string>;
}

