/**
 *  Esquire frameworks (tm)
 *  Esqurie rest client
 *
 * Copyright(c) 2021, 2025 mir0n&co www.mir0n.me
 * mailto:mir0n.the.programmer@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


/**
 * User Permission
 */
export interface EsqPermission { 
    /**
     * Permission ID
     */
    id?: string;
    /**
     * Kind  of user were access defined
     */
    kind?: number;
    /**
     * Type of permission
     */
    name?: string;
    /**
     * Type of permission
     */
    type?: string;
    /**
     * Permission Y/N flags: create, update, delete, security, accounting
     */
    flags?: Array<string>;
}

