/**
 *  Esquire frameworks (tm)
 *  Esqurie rest client
 *
 * Copyright(c) 2021, 2025 mir0n&co www.mir0n.me
 * mailto:mir0n.the.programmer@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


/**
 * Access Profile of a user
 */
export interface EsqRole { 
    /**
     * Role ID
     */
    id?: number;
    /**
     * Role Name
     */
    name?: string;
    /**
     * Role Name
     */
    adminFlg?: string;
}

