/**
 *  Esquire frameworks (tm)
 *  Esqurie rest client
 *
 * Copyright(c) 2021, 2025 mir0n&co www.mir0n.me
 * mailto:mir0n.the.programmer@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */


/**
 * A node with all information for tree navigation
 */
export interface EsqTreeNode { 
    /**
     * node id
     */
    id?: string;
    /**
     * Node type, odd types are \'short cuts\' a link node referencing to origin one
     */
    kind?: number;
    /**
     * Node name
     */
    name?: string;
    /**
     * Parent node id
     */
    parentId?: string;
    /**
     * For shortcut nodes, reference to the origin node
     */
    linkId?: string;
    /**
     * Entity id (it can be different from node id)
     */
    entityId?: string;
    /**
     * Node Status Code, (0)ok (1)deleted (2)locked, (3)checked (4)question
     */
    statusCode?: EsqTreeNode.StatusCodeEnum;
    /**
     * Indicates when more nodes left to retrieve
     */
    moreRemaining?: boolean;
    /**
     * Tree level of node
     */
    level?: number;
    /**
     * Node path on the tree
     */
    path?: Array<string>;
    /**
     * Node description
     */
    desc?: string;
}
export namespace EsqTreeNode {
    export const StatusCodeEnum = {
        NUMBER_0: 0,
        NUMBER_1: 1,
        NUMBER_2: 2,
        NUMBER_3: 3,
        NUMBER_4: 4
    } as const;
    export type StatusCodeEnum = typeof StatusCodeEnum[keyof typeof StatusCodeEnum];
}


