/**
 *  Esquire frameworks (tm)
 *  Esqurie rest client
 *
 * Copyright(c) 2021, 2025 mir0n&co www.mir0n.me
 * mailto:mir0n.the.programmer@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */
import { ProblemDetailFieldError } from './problemDetailFieldError';


/**
 * the extra members Esquire sets on every problem
 */
export interface ProblemDetailProperties { 
    timestamp?: string;
    traceId?: string;
    correlationId?: string;
    /**
     * present when the caller sent one
     */
    requestId?: string;
    /**
     * present only when the request asked for metric capture
     */
    stackTrace?: string;
    /**
     * present on a validation error
     */
    errors?: Array<ProblemDetailFieldError>;
}

