/**
 *  Esquire frameworks (tm)
 *  Esqurie rest client
 *
 * Copyright(c) 2021, 2025 mir0n&co www.mir0n.me
 * mailto:mir0n.the.programmer@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit the class manually.
 */
import { ProblemDetailProperties } from './problemDetailProperties';


/**
 * The error body every Esquire service returns (RFC 7807, as Spring writes it). Served as application/problem+json.
 */
export interface ProblemDetail { 
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    /**
     * the request path that produced the error
     */
    instance?: string;
    properties?: ProblemDetailProperties;
}

