/*
*  Esquire frameworks (tm)
*  Esquire Explorer
*  Copyright(c) 2001, 2025 mir0n&co www.mir0n.me
*  mailto:mir0n.the.programmer@gmail.com
*
*  History:
* 05/07/2026 mir0n  created: X-Request-ID generated per request; Math.random fallback when crypto.randomUUID is unavailable on non-secure-context origins (e.g. host.docker.internal)
*/

import { HttpInterceptorFn } from '@angular/common/http';

// Esquire REST client tracing convention:
//   X-Request-ID     - required; one UUID per outbound HTTP, client-generated.
//   X-Correlation-ID - server-generated by default; uncomment the line below
//                      only to debug-trace a specific request across services.
//   X-Capture-Metrics - marks the request for metrics capture.
//
// crypto.randomUUID() is only available in secure contexts (HTTPS or localhost).
// On plain HTTP non-localhost hosts (e.g. host.docker.internal:4200 in local k8s),
// it's undefined and throws. Fall back to a Math.random()-based UUID -- not
// crypto-strong, but tracing IDs don't need to be: just unique per request.
const newRequestId = (): string => {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  // RFC 4122 v4-shaped pseudo-random id; sufficient for log correlation.
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16);
  });
};

export const tracingInterceptor: HttpInterceptorFn = (req, next) => {
  const requestId = newRequestId();

  const modifiedReq = req.clone({
    headers: req.headers
      .set('X-Request-ID', requestId)
      //.set('X-Correlation-ID', requestId + '-CID')
      .set('X-Capture-Metrics', 'true')
  });

  return next(modifiedReq);
};
